openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/readFile:
    get:
      summary: 'Read File'
      description: ''
      parameters:
        -
          in: query
          name: url
          description: ''
          example: auth.log
          required: true
          schema:
            type: string
            description: ''
            example: auth.log
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     \"May 23 12:09:01 abdelaziz CRON[1412]: pam_unix(cron:session): session opened for user root by (uid=0)\",\n      \"May 23 12:09:01 abdelaziz CRON[1412]: pam_unix(cron:session): session closed for user root\"\n}"
      tags:
        - Authentication
      security: []
tags:
  -
    name: Authentication
    description: "\nAPI endpoints for managing files"
